#!/bin/bash

# if no $1, say environment is required
if [ -z "$1" ]; then
  echo "Error: environment is required"
  exit 1
fi

# Source the .env file
source .env

# Copy the example file to the output file
cp fly.toml.template fly.toml

# add 
## AUTOGENERATED FILE 
## DO NOT MODIFY BY HAND 
# to the top
sed -i '1s/^/## AUTOGENERATED FILE\n## DO NOT MODIFY BY HAND\n\n/' fly.toml

# create PALMETTO_APP_NAME_HYPHENS and PALMETTO_APP_NAME_UNDERSCORES from PALMETTO_APP_NAME
PALMETTO_APP_NAME="${PALMETTO_APP_NAME}-$1"
PALMETTO_APP_NAME_HYPHENS=$(echo "$PALMETTO_APP_NAME" | sed 's/_/-/g')
PALMETTO_APP_NAME_UNDERSCORES=$(echo "$PALMETTO_APP_NAME" | sed 's/-/_/g')

# replace PALMETTO_APP_NAME_HYPHENS and PALMETTO_APP_NAME_UNDERSCORES in fly.toml
sed -i "s|PALMETTO_APP_NAME_HYPHENS|${PALMETTO_APP_NAME_HYPHENS}|g" fly.toml
sed -i "s|PALMETTO_APP_NAME_UNDERSCORES|${PALMETTO_APP_NAME_UNDERSCORES}|g" fly.toml

# create PALMETTO_VM_SIZE_STRING # generated by the script, either like shared-cpu-8x or performance-16x from PALMETTO_VM_VCPU_TYPE of "shared" or "performance" and PALMETTO_VM_VCPU_COUNT of a number
if [ $PALMETTO_VM_VCPU_TYPE = "shared" ]; then
  PALMETTO_VM_SIZE_STRING="shared-cpu-${PALMETTO_VM_VCPU_COUNT}x"
elif [ $PALMETTO_VM_VCPU_TYPE = "performance" ]; then
  PALMETTO_VM_SIZE_STRING="performance-${PALMETTO_VM_VCPU_COUNT}x"
else
  echo "Error: PALMETTO_VM_VCPU_TYPE must be either 'shared' or 'performance'"
  exit 1
fi

# replace PALMETTO_VM_SIZE_STRING in fly.toml
sed -i "s|PALMETTO_VM_SIZE_STRING|${PALMETTO_VM_SIZE_STRING}|g" fly.toml


# Loop over the lines in the .env file
while IFS='=' read -r VAR_NAME VAR_VALUE
do
  # Check if VAR_NAME is not empty
  if [ -n "$VAR_NAME" ]; then
    # Use sed to replace the placeholder with the actual value in the output file
    # Use different delimiter to avoid conflict with slashes in VAR_VALUE
    sed -i "s|${VAR_NAME}|${VAR_VALUE}|g" fly.toml
  fi
done < .env